---
# USER-SERVICE - Base de données PostgreSQL

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql-user-data
  namespace: production
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

---
apiVersion: v1
kind: Service
metadata:
  name: postgresql-user
  namespace: production
  labels:
    app: postgresql-user
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: postgresql-user

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql-user
  namespace: production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresql-user
  template:
    metadata:
      labels:
        app: postgresql-user
    spec:
      containers:
      - name: postgresql
        image: postgres:16-alpine
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          value: user_db
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: user-db-secrets
              key: username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: user-db-secrets
              key: password
        volumeMounts:
        - name: data
          mountPath: /var/lib/postgresql/data
          subPath: postgres
        livenessProbe:
          exec:
            command:
              - /bin/sh
              - -c
              - pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}
          initialDelaySeconds: 30
          periodSeconds: 10
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: postgresql-user-data

---
apiVersion: v1
kind: Secret
metadata:
  name: user-db-secrets
  namespace: production
type: Opaque
stringData:
  username: user_user
  password: user_password_123

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: user-service-config
  namespace: production
data:
  QUARKUS_DATASOURCE_JDBC_URL: "jdbc:postgresql://postgresql-user:5432/user_db"
  QUARKUS_DATASOURCE_USERNAME: "user_user"
  QUARKUS_DATASOURCE_PASSWORD: "user_password_123"
  QUARKUS_HTTP_HOST: "0.0.0.0"
  QUARKUS_HTTP_PORT: "8080"

---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: production
  labels:
    app: user-service
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 8080
  selector:
    app: user-service

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: production
  labels:
    app: user-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-service
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
      - name: user-service
        image: registry.gitlab.com/b-s-m/user-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 8080
        envFrom:
        - configMapRef:
            name: user-service-config
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /q/health/live
            port: 8080
          initialDelaySeconds: 90
          periodSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /q/health/ready
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 5
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /q/health/started
            port: 8080
          failureThreshold: 60
          periodSeconds: 2
